name: Get Lines of Code for GitHub Organizations

on:
  workflow_dispatch:
    inputs:
      test_org_name:
        description: 'Name of the TEST environment GitHub Organization(s)'
        required: true
        default: ''
      prod_org_name:
        description: 'Name of the PROD environment GitHub Organization(s)'
        required: true
        default: ''

env:
  ORG_PERSONAL_ACCESS_TOKEN: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0

      - name: Install Dependencies
        run: sudo apt-get install -y cloc

      - name: Calculating LoC for TEST organizations
        env:
          GITHUB_TOKEN: ${{ env.ORG_PERSONAL_ACCESS_TOKEN }}
        run: |
          IFS=',' read -ra ORGS <<< "${{ github.event.inputs.test_org_name }}"
          for org in "${ORGS[@]}"; do
            bundle exec ruby loc.rb "$org"
          done

  prod:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.0

      - name: Install Dependencies
        run: sudo apt-get install -y cloc

      - name: Calculating LoC for PROD organizations
        env:
          GITHUB_TOKEN: ${{ env.ORG_PERSONAL_ACCESS_TOKEN }}
        run: |
          IFS=',' read -ra ORGS <<< "${{ github.event.inputs.prod_org_name }}"
          for org in "${ORGS[@]}"; do
            bundle exec ruby loc.rb "$org"
          done
